version: build-{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Calcex.sln
  verbosity: minimal
after_build:
- cmd: >-
    set VersionSuffix=build%APPVEYOR_BUILD_NUMBER%

    dotnet pack Calcex.Core
test:
  assemblies:
    only:
    - '**\Calcex.Tests.dll'
artifacts:
- path: '**\*.nupkg'