version: 0.2.0-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: Calcex.Core.sln
  verbosity: minimal
after_build:
- cmd: >-
    set VersionSuffix=alpha%APPVEYOR_BUILD_NUMBER%

    dotnet pack Calcex.Core
test:
  assemblies:
    only:
    - '**\Calcex.Tests.dll'
artifacts:
- path: '**\*.nupkg'